# General
site_name: VLNT
css_path: inc/style.css
template_dir: templates/

# Navigation
menu:
  - title: Home
    slug: index
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAACXBIWXMAAC4jAAAuIwF4pT92AAAAUElEQVQ4y81TOQ4AMAgS//9nujaNRywdyqYSAx6wGEzysAYMYlYcNxEoJGPLo+DoFig4oE+nfHIgKtC3YI0CdnUfNEu3AOWO/jikJ79w/c4LRsAdA34hQFwAAAAASUVORK5CYII="
  - title: Books
    slug: books
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAMAAAAECAYAAABLLYUHAAAACXBIWXMAAC4jAAAuIwF4pT92AAAAGUlEQVQI12NgYGD4D8UMjDAGCDBBaUYMGQCIJgQCsZKYkAAAAABJRU5ErkJggg=="
  - title: Code
    slug: code
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAMAAAAECAYAAABLLYUHAAAACXBIWXMAAC4jAAAuIwF4pT92AAAAF0lEQVQI12NkYGD4z4AE4BwmZFFGZBkAXE0DAgem7doAAAAASUVORK5CYII="
  - title: Other
    slug: other
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAMAAAAECAYAAABLLYUHAAAACXBIWXMAAC4jAAAuIwF4pT92AAAAGUlEQVQI12NkYGD4zwAFTFCaEZkDF4ErAwA53QIGnU/NDAAAAABJRU5ErkJggg=="
  - title: Quotes
    slug: quotes
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAMAAAAECAYAAABLLYUHAAAACXBIWXMAAC4jAAAuIwF4pT92AAAAGUlEQVQI12NkYGD4zwAFTFCaEUbAZZDBfwBHqAMDl78yDAAAAABJRU5ErkJggg=="
  - title: Text
    slug: text
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAMAAAAECAYAAABLLYUHAAAACXBIWXMAAC4jAAAuIwF4pT92AAAAFklEQVQI12NkYGD4z4AGwAJMyCIoHABPZwIE9eCI+AAAAABJRU5ErkJggg=="
  - title: [Up]
    slug: #
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAMAAAAECAYAAABLLYUHAAAACXBIWXMAAC4jAAAuIwF4pT92AAAAF0lEQVQI12NggID/IIIRxkAGYAEmZBEAYRQDAWN3Wf0AAAAASUVORK5CYII="
  - title: [Down]
    slug: #bottom
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAMAAAAECAYAAABLLYUHAAAACXBIWXMAAC4jAAAuIwF4pT92AAAAGElEQVQI12NggID/IIKJAQkwwkSRAVgAAEdVAwFW/w2ZAAAAAElFTkSuQmCC"
